### ISSUE TITLE
Complexity of intersection

### ISSUE THREAD

**Issue by lmcarreiro** [scottjulian/LCS#2]
Hi, I'm studying your algorithm, there is some things that I still need to understand, but you said in your blog that:

> The time complexity of this function is **O(k²n)** where **k** is the number of sequences and **n** is number of pairs in a sequence pair list.

So, I have a question about this line of your pseudo-code:
```diff
intersectingPairs(pairList[])  
    init intersectedPairs[]
    for i = 0 through number of pairLists
        for j = 0 through number of pairs in pairList[i]
            init count = 1
            for k = 0 through number of pairLists
+                if pairList[i][j] exists in pairList[k] && k != i
                    increment count
            if count == number of pairLists
                interesectedPairs += pairList[i][j]
    return intersectedPairs
```

This could be **O(1)** if you use a java's HashSet, but in your code you make it **O(n)**, using a loop and comparing `pairList[i][j]` with each pair in `pairList[k]`.

The result of **O(k²n)** that you mention in your blog post, did you consider this `pairList[i][j] exists in pairList[k]` operation as **O(1)** or **O(n)**?

**Comment by scottjulian** [comment]
Thanks for your interest in this project. Unfortunately I wrote this code over 6 years ago, despite it being on GH for 2. I no longer maintain this project project and simply host it for posterity. I wrote it for the understanding of LCS, and not a perfect optimized solution.

However if you wish to optimize it and make the code better, I definitely recommend forking it and submitting a pull request.

Thanks

**Comment by lmcarreiro** [comment]
I got it.
Are you the author of this algorithm or did you just made a blog post explaining it?

**Comment by scottjulian** [comment]
Both. However finding the LCS isn't something I discovered, this is a very well-known problem exists and I implore you to search for more better information on this if you are interested.

**Comment by lmcarreiro** [comment]
It is what I'm doing, but I didn't find much information about the LCS with unknown number of sequences as input. I've only found information about LCS between only two sequences.
Your solution was the first I've found.
Thanks.
